export const wasteMap = {
  // 1. PAPER & CARDBOARD PACKAGING (papp- ja paberpakend)
  'paper towel':         'papp- ja paberpakend',
  'envelope':            'papp- ja paberpakend',
  'book jacket':         'papp- ja paberpakend',
  'carton':              'papp- ja paberpakend',
  'cardboard box':       'papp- ja paberpakend',
  'cereal box':          'papp- ja paberpakend',
  'egg carton':          'papp- ja paberpakend',
  'pizza box':           'papp- ja paberpakend',
  'notebook':            'papp- ja paberpakend',
  'paper bag':           'papp- ja paberpakend',
  'newspaper':           'papp- ja paberpakend',
  'magazine':            'papp- ja paberpakend',
  'flyer':               'papp- ja paberpakend',
  'brochure':            'papp- ja paberpakend',
  'catalog':             'papp- ja paberpakend',
  'gift wrap':           'papp- ja paberpakend',
  'toilet paper roll':   'papp- ja paberpakend',
  'paper cup':           'papp- ja paberpakend',
  'greeting card':       'papp- ja paberpakend',
  'poster':              'papp- ja paberpakend',
  'paper plate':         'papp- ja paberpakend',
  'tissue box':          'papp- ja paberpakend',
  'paper folder':        'papp- ja paberpakend',
  'paper file':          'papp- ja paberpakend',
  'menu card':           'papp- ja paberpakend',
  'business card':       'papp- ja paberpakend',
  'receipt':             'papp- ja paberpakend',
  'paper label':         'papp- ja paberpakend',
  'postcard':            'papp- ja paberpakend',
  'kraft paper':         'papp- ja paberpakend',
  'cardboard tube':      'papp- ja paberpakend',
  'paper packaging':     'papp- ja paberpakend',
  'gift box':            'papp- ja paberpakend',
  'paper container':     'papp- ja paberpakend',
  'document sleeve':     'papp- ja paberpakend',
  'paper file folder':   'papp- ja paberpakend',
  'paperboard':          'papp- ja paberpakend',
  'corrugated box':      'papp- ja paberpakend',
  'shoe box':            'papp- ja paberpakend',
  'cardboard sleeve':    'papp- ja paberpakend',
  'paper divider':       'papp- ja paberpakend',
  'paper bookmark':      'papp- ja paberpakend',
  'paper tag':           'papp- ja paberpakend',
  'paper coaster':       'papp- ja paberpakend',
  'paper tube':          'papp- ja paberpakend',
  'paper board':         'papp- ja paberpakend',
  'cardboard backing':   'papp- ja paberpakend',
  'paper insert':        'papp- ja paberpakend',
  'gift card holder':    'papp- ja paberpakend',
  'product packaging':   'papp- ja paberpakend',
  'cardboard carton':    'papp- ja paberpakend',
  'shipping box':        'papp- ja paberpakend',
  'moving box':          'papp- ja paberpakend',
  'book box':            'papp- ja paberpakend',
  'paper roll core':     'papp- ja paberpakend',
  'paper sack':          'papp- ja paberpakend',
  'paper sleeve':        'papp- ja paberpakend',
  'paper wrapper':       'papp- ja paberpakend',
  'paper envelope':      'papp- ja paberpakend',
  'manila envelope':     'papp- ja paberpakend',
  'bubble mailer':       'papp- ja paberpakend',
  'paper mailer':        'papp- ja paberpakend',
  'wine box':            'papp- ja paberpakend',
  'beer carrier':        'papp- ja paberpakend',
  'six-pack carrier':    'papp- ja paberpakend',
  'donut box':           'papp- ja paberpakend',
  'cake box':            'papp- ja paberpakend',
  'chocolate box':       'papp- ja paberpakend',
  'tea box':             'papp- ja paberpakend',
  'cookie package':      'papp- ja paberpakend',
  'cardboard display':   'papp- ja paberpakend',
  'paper calendar':      'papp- ja paberpakend',
  'paper notepad':       'papp- ja paberpakend',
  'paper dossier':       'papp- ja paberpakend',
  'cardboard frame':     'papp- ja paberpakend',
  'paper shopping bag':  'papp- ja paberpakend',
  'paper gift bag':      'papp- ja paberpakend',
  'takeout container':   'papp- ja paberpakend',
  'takeout box':         'papp- ja paberpakend',
  'paper napkin':        'papp- ja paberpakend',
  'paper tray':          'papp- ja paberpakend',
  'paper box':           'papp- ja paberpakend',
  'index card':          'papp- ja paberpakend',
  'paper stationery':    'papp- ja paberpakend',
  'grocery bag':         'papp- ja paberpakend',
  'bakery bag':          'papp- ja paberpakend',
  'comic book':          'papp- ja paberpakend',
  'paper manual':        'papp- ja paberpakend',
  'instruction manual':  'papp- ja paberpakend',
  'paper drink carrier': 'papp- ja paberpakend',
  'paper cup sleeve':    'papp- ja paberpakend',
  'paper folder divider':'papp- ja paberpakend',
  'paper file tab':      'papp- ja paberpakend',
  'mailing tube':        'papp- ja paberpakend',
  'desk organizer':      'papp- ja paberpakend',
  'paper clip box':      'papp- ja paberpakend',
  'fastener box':        'papp- ja paberpakend',
  'paper case':          'papp- ja paberpakend',
  'book binding':        'papp- ja paberpakend',
  
  // 2. PLASTIC & METAL PACKAGING (plast- ja metallpakend)
  'plastic bag':         'plast- ja metallpakend',
  'pop bottle':          'plast- ja metallpakend',
  'soda bottle':         'plast- ja metallpakend',
  'pill bottle':         'plast- ja metallpakend',
  'milk can':            'plast- ja metallpakend',
  'can opener':          'plast- ja metallpakend',
  'bucket':              'plast- ja metallpakend',
  'barrel':              'plast- ja metallpakend',
  'drum':                'plast- ja metallpakend',
  'tray':                'plast- ja metallpakend',
  'plastic container':   'plast- ja metallpakend',
  'yogurt cup':          'plast- ja metallpakend',
  'plastic wrap':        'plast- ja metallpakend',
  'beverage can':        'plast- ja metallpakend',
  'aluminum foil':       'plast- ja metallpakend',
  'soda can':            'plast- ja metallpakend',
  'beer can':            'plast- ja metallpakend',
  'food tin':            'plast- ja metallpakend',
  'spray can':           'plast- ja metallpakend',
  'metal lid':           'plast- ja metallpakend',
  'bottle cap':          'plast- ja metallpakend',
  'plastic cutlery':     'plast- ja metallpakend',
  'plastic straw':       'plast- ja metallpakend',
  'shampoo bottle':      'plast- ja metallpakend',
  'detergent bottle':    'plast- ja metallpakend',
  'cosmetic container':  'plast- ja metallpakend',
  'toothpaste tube':     'plast- ja metallpakend',
  'deodorant can':       'plast- ja metallpakend',
  'cookie tin':          'plast- ja metallpakend',
  'plastic cup':         'plast- ja metallpakend',
  'plastic tub':         'plast- ja metallpakend',
  'margarine tub':       'plast- ja metallpakend',
  'juice box':           'plast- ja metallpakend',
  'milk carton':         'plast- ja metallpakend',
  'bubble wrap':         'plast- ja metallpakend',
  'shopping bag':        'plast- ja metallpakend',
  'six-pack rings':      'plast- ja metallpakend',
  'coffee capsule':      'plast- ja metallpakend',
  'sauce packet':        'plast- ja metallpakend',
  'candy wrapper':       'plast- ja metallpakend',
  'chip bag':            'plast- ja metallpakend',
  'blister pack':        'plast- ja metallpakend',
  'paint can':           'plast- ja metallpakend',
  'aerosol can':         'plast- ja metallpakend',
  'aluminum tray':       'plast- ja metallpakend',
  'aluminum pan':        'plast- ja metallpakend',
  'tin can':             'plast- ja metallpakend',
  'metal bottle':        'plast- ja metallpakend',
  'metal container':     'plast- ja metallpakend',
  'spray bottle':        'plast- ja metallpakend',
  'trigger sprayer':     'plast- ja metallpakend',
  'pump dispenser':      'plast- ja metallpakend',
  'lotion bottle':       'plast- ja metallpakend',
  'conditioner bottle':  'plast- ja metallpakend',
  'body wash bottle':    'plast- ja metallpakend',
  'soap dispenser':      'plast- ja metallpakend',
  'hand sanitizer':      'plast- ja metallpakend',
  'plastic jar':         'plast- ja metallpakend',
  'plastic pot':         'plast- ja metallpakend',
  'plastic tube':        'plast- ja metallpakend',
  'plastic pouch':       'plast- ja metallpakend',
  'plastic sachet':      'plast- ja metallpakend',
  'plastic film':        'plast- ja metallpakend',
  'shrink wrap':         'plast- ja metallpakend',
  'stretch film':        'plast- ja metallpakend',
  'plastic lid':         'plast- ja metallpakend',
  'plastic cap':         'plast- ja metallpakend',
  'plastic seal':        'plast- ja metallpakend',
  'plastic ring':        'plast- ja metallpakend',
  'plastic case':        'plast- ja metallpakend',
  'plastic clamshell':   'plast- ja metallpakend',
  'plastic box':         'plast- ja metallpakend',
  'plastic carton':      'plast- ja metallpakend',
  'plastic basket':      'plast- ja metallpakend',
  'plastic crate':       'plast- ja metallpakend',
  'plastic pallet':      'plast- ja metallpakend',
  'plastic handle':      'plast- ja metallpakend',
  'plastic scoop':       'plast- ja metallpakend',
  'plastic measuring cup':'plast- ja metallpakend',
  'plastic funnel':      'plast- ja metallpakend',
  'plastic dropper':     'plast- ja metallpakend',
  'plastic applicator':  'plast- ja metallpakend',
  'plastic spoon':       'plast- ja metallpakend',
  'plastic fork':        'plast- ja metallpakend',
  'plastic knife':       'plast- ja metallpakend',
  'plastic stirrer':     'plast- ja metallpakend',
  'plastic plate':       'plast- ja metallpakend',
  'plastic bowl':        'plast- ja metallpakend',
  'plastic mug':         'plast- ja metallpakend',
  'plastic tumbler':     'plast- ja metallpakend',
  'plastic pitcher':     'plast- ja metallpakend',
  'plastic jug':         'plast- ja metallpakend',
  'plastic canister':    'plast- ja metallpakend',
  'plastic gallon':      'plast- ja metallpakend',
  'plastic tank':        'plast- ja metallpakend',
  'plastic drum':        'plast- ja metallpakend',
  'plastic barrel':      'plast- ja metallpakend',
  'plastic bin':         'plast- ja metallpakend',
  'metal tube':          'plast- ja metallpakend',
  'metal can':           'plast- ja metallpakend',
  'metal box':           'plast- ja metallpakend',
  'metal keg':           'plast- ja metallpakend',
  'metal drum':          'plast- ja metallpakend',
  'metal barrel':        'plast- ja metallpakend',
  
  // 3. GLASS PACKAGING (klaaspakend)
  'wine bottle':         'klaaspakend',
  'beer bottle':         'klaaspakend',
  'water bottle':        'klaaspakend',
  'beer glass':          'klaaspakend',
  'goblet':              'klaaspakend',
  'pitcher':             'klaaspakend',
  'jam jar':             'klaaspakend',
  'pickle jar':          'klaaspakend',
  'olive jar':           'klaaspakend',
  'baby food jar':       'klaaspakend',
  'sauce jar':           'klaaspakend',
  'perfume bottle':      'klaaspakend',
  'liquor bottle':       'klaaspakend',
  'medicine bottle':     'klaaspakend',
  'spice jar':           'klaaspakend',
  'glass vial':          'klaaspakend',
  'glass ampoule':       'klaaspakend',
  'glass flask':         'klaaspakend',
  'shot glass':          'klaaspakend',
  'juice bottle':        'klaaspakend',
  'syrup bottle':        'klaaspakend',
  'vinegar bottle':      'klaaspakend',
  'oil bottle':          'klaaspakend',
  'cosmetic jar':        'klaaspakend',
  'glass container':     'klaaspakend',
  'whiskey bottle':      'klaaspakend',
  'vodka bottle':        'klaaspakend',
  'gin bottle':          'klaaspakend',
  'rum bottle':          'klaaspakend',
  'tequila bottle':      'klaaspakend',
  'brandy bottle':       'klaaspakend',
  'champagne bottle':    'klaaspakend',
  'sparkling wine bottle':'klaaspakend',
  'cider bottle':        'klaaspakend',
  'soda glass bottle':   'klaaspakend',
  'mineral water bottle': 'klaaspakend',
  'glass milk bottle':   'klaaspakend',
  'cocktail glass':      'klaaspakend',
  'highball glass':      'klaaspakend',
  'lowball glass':       'klaaspakend',
  'wine glass':          'klaaspakend',
  'martini glass':       'klaaspakend',
  'margarita glass':     'klaaspakend',
  'cognac glass':        'klaaspakend',
  'champagne flute':     'klaaspakend',
  'glass tumbler':       'klaaspakend',
  'glass jar':           'klaaspakend',
  'preserving jar':      'klaaspakend',
  'canning jar':         'klaaspakend',
  'mason jar':           'klaaspakend',
  'kilner jar':          'klaaspakend',
  'glass canister':      'klaaspakend',
  'glass bottle':        'klaaspakend',
  'coffee jar':          'klaaspakend',
  'glass honey jar':     'klaaspakend',
  'glass candy jar':     'klaaspakend',
  'glass storage jar':   'klaaspakend',
  'glass peanut butter jar':'klaaspakend',
  'glass pickle jar':    'klaaspakend',
  'glass mustard jar':   'klaaspakend',
  'glass relish jar':    'klaaspakend',
  'glass salsa jar':     'klaaspakend',
  'glass jelly jar':     'klaaspakend',
  'glass preserves jar': 'klaaspakend',
  'glass chutney jar':   'klaaspakend',
  'glass spread jar':    'klaaspakend',
  'glass herb jar':      'klaaspakend',
  'glass seasoning jar': 'klaaspakend',
  'glass salt jar':      'klaaspakend',
  'glass pepper jar':    'klaaspakend',
  'glass decanter':      'klaaspakend',
  'glass carafe':        'klaaspakend',
  'glass medicine bottle':'klaaspakend',
  'glass dropper bottle':'klaaspakend',
  'glass essential oil bottle':'klaaspakend',
  'glass cologne bottle':'klaaspakend',
  'glass aftershave bottle':'klaaspakend',
  'glass cream jar':     'klaaspakend',
  'glass moisturizer jar':'klaaspakend',
  'glass serum bottle':  'klaaspakend',
  'glass lotion bottle': 'klaaspakend',
  'glass foundation bottle':'klaaspakend',
  'glass nail polish bottle':'klaaspakend',
  'glass eye dropper':   'klaaspakend',
  'glass spray bottle':  'klaaspakend',
  'glass atomizer':      'klaaspakend',
  'glass ampule':        'klaaspakend',
  
  // 4. BIO-WASTE (biojäätmed)
  'banana':              'biojäätmed',
  'apple':               'biojäätmed',
  'orange':              'biojäätmed',
  'lemon':               'biojäätmed',
  'broccoli':            'biojäätmed',
  'cauliflower':         'biojäätmed',
  'cucumber':            'biojäätmed',
  'bell pepper':         'biojäätmed',
  'potato peel':         'biojäätmed',
  'carrot peel':         'biojäätmed',
  'onion skin':          'biojäätmed',
  'coffee grounds':      'biojäätmed',
  'tea bag':             'biojäätmed',
  'egg shell':           'biojäätmed',
  'bread':               'biojäätmed',
  'cheese rind':         'biojäätmed',
  'fish bones':          'biojäätmed',
  'meat bones':          'biojäätmed',
  'spoiled food':        'biojäätmed',
  'leftover meal':       'biojäätmed',
  'garden waste':        'biojäätmed',
  'grass clippings':     'biojäätmed',
  'leaves':              'biojäätmed',
  'branches':            'biojäätmed',
  'flowers':             'biojäätmed',
  'houseplant':          'biojäätmed',
  'sawdust':             'biojäätmed',
  'wood chips':          'biojäätmed',
  'nut shells':          'biojäätmed',
  'fruit pits':          'biojäätmed',
  'corn cob':            'biojäätmed',
  'paper napkin soiled': 'biojäätmed',
  'paper towel soiled':  'biojäätmed',
  'pizza crust':         'biojäätmed',
  'pasta':               'biojäätmed',
  'rice':                'biojäätmed',
  'cereal':              'biojäätmed',
  'potato':              'biojäätmed',
  'tomato':              'biojäätmed',
  'strawberry':          'biojäätmed',
  'grape':               'biojäätmed',
  'mushroom':            'biojäätmed',
  'pineapple':           'biojäätmed',
  'watermelon':          'biojäätmed',
  'pear':                'biojäätmed',
  'avocado':             'biojäätmed',
  'peach':               'biojäätmed',
  'garlic':              'biojäätmed',
  'ginger':              'biojäätmed',
  'mango':               'biojäätmed',
  'kiwi':                'biojäätmed',
  'plum':                'biojäätmed',
  'cherry':              'biojäätmed',
  'blueberry':           'biojäätmed',
  'raspberry':           'biojäätmed',
  'blackberry':          'biojäätmed',
  'cranberry':           'biojäätmed',
  'gooseberry':          'biojäätmed',
  'melon':               'biojäätmed',
  'papaya':              'biojäätmed',
  'apricot':             'biojäätmed',
  'nectarine':           'biojäätmed',
  'fig':                 'biojäätmed',
  'date':                'biojäätmed',
  'pomegranate':         'biojäätmed',
  'lime':                'biojäätmed',
  'banana peel':         'biojäätmed',
  'apple core':          'biojäätmed',
  'orange peel':         'biojäätmed',
  'lemon peel':          'biojäätmed',
  'potato skin':         'biojäätmed',
  'carrot top':          'biojäätmed',
  'onion layer':         'biojäätmed',
  'garlic skin':         'biojäätmed',
  'corn husk':           'biojäätmed',
  'pea pod':             'biojäätmed',
  'bean pod':            'biojäätmed',
  'walnut shell':        'biojäätmed',
  'almond shell':        'biojäätmed',
  'pistachio shell':     'biojäätmed',
  'peanut shell':        'biojäätmed',
  'shrimp shell':        'biojäätmed',
  'crab shell':          'biojäätmed',
  'lobster shell':       'biojäätmed',
  'oyster shell':        'biojäätmed',
  'mussel shell':        'biojäätmed',
  'clam shell':          'biojäätmed', 
  'coconut shell':       'biojäätmed',
  'coconut husk':        'biojäätmed',
  'avocado pit':         'biojäätmed',
  'peach pit':           'biojäätmed',
  'cherry pit':          'biojäätmed',
  'olive pit':           'biojäätmed',
  'mango pit':           'biojäätmed',
  'watermelon rind':     'biojäätmed',
  'cantaloupe rind':     'biojäätmed',
  'honeydew rind':       'biojäätmed',
  'pumpkin skin':        'biojäätmed',
  'squash skin':         'biojäätmed',
  'zucchini skin':       'biojäätmed',
  'cucumber peel':       'biojäätmed',
  'eggplant skin':       'biojäätmed',
  'pepper stem':         'biojäätmed',
  'cabbage core':        'biojäätmed',
  'lettuce core':        'biojäätmed',
  'celery base':         'biojäätmed',
  'pineapple top':       'biojäätmed',
  'pineapple skin':      'biojäätmed',
  
  // 5. MIXED RESIDUAL WASTE (olmejäätmed)
  'ashcan':              'olmejäätmed',
  'trash can':           'olmejäätmed',
  'garbage can':         'olmejäätmed',
  'wastebin':            'olmejäätmed',
  'diaper':              'olmejäätmed',
  'syringe':             'olmejäätmed',
  'toilet tissue':       'olmejäätmed',
  'safety pin':          'olmejäätmed',
  'screw':               'olmejäätmed',
  'nail':                'olmejäätmed',
  'shoe':                'olmejäätmed',
  'running shoe':        'olmejäätmed',
  'sock':                'olmejäätmed',
  'cigarette butt':      'olmejäätmed',
  'dust bag':            'olmejäätmed',
  'vacuum cleaner bag':  'olmejäätmed',
  'cotton swab':         'olmejäätmed',
  'cotton ball':         'olmejäätmed',
  'band-aid':            'olmejäätmed',
  'toothbrush':          'olmejäätmed',
  'dental floss':        'olmejäätmed',
  'rubber glove':        'olmejäätmed',
  'pet waste':           'olmejäätmed',
  'cat litter':          'olmejäätmed',
  'light bulb':          'olmejäätmed',
  'broken glass':        'olmejäätmed',
  'ceramic':             'olmejäätmed',
  'porcelain':           'olmejäätmed',
  'mirror':              'olmejäätmed',
  'styrofoam':           'olmejäätmed',
  'chewing gum':         'olmejäätmed',
  'pen':                 'olmejäätmed',
  'marker':              'olmejäätmed',
  'pencil':              'olmejäätmed',
  'eraser':              'olmejäätmed',
  'tape':                'olmejäätmed',
  'sticker':             'olmejäätmed',
  'credit card':         'olmejäätmed',
  'ribbon':              'olmejäätmed',
  'balloon':             'olmejäätmed',
  'candle':              'olmejäätmed',
  'comb':                'olmejäätmed',
  'sponge':              'olmejäätmed',
  'rubber band':         'olmejäätmed',
  'cd disc':             'olmejäätmed',
  'dvd disc':            'olmejäätmed',
  'cassette tape':       'olmejäätmed',
  'photograph':          'olmejäätmed',
  'polaroid':            'olmejäätmed',
  'razor blade':         'olmejäätmed',
  'disposable razor':    'olmejäätmed',
  'makeup brush':        'olmejäätmed',
  'lint roller sheet':   'olmejäätmed',
  'hair brush':          'olmejäätmed',
  'hair clip':           'olmejäätmed',
  'hair band':           'olmejäätmed',
  'hair tie':            'olmejäätmed',
  'bobby pin':           'olmejäätmed',
  'barrette':            'olmejäätmed',
  'scrunchie':           'olmejäätmed',
  'sanitary pad':        'olmejäätmed',
  'tampon':              'olmejäätmed',
  'condom':              'olmejäätmed',
  'dental pick':         'olmejäätmed',
  'contact lens':        'olmejäätmed',
  'contact case':        'olmejäätmed',
  'eyeglasses':          'olmejäätmed',
  'sunglasses':          'olmejäätmed',
  'watch':               'olmejäätmed',
  'watch band':          'olmejäätmed',
  'jewelry':             'olmejäätmed',
  'earring':             'olmejäätmed',
  'necklace':            'olmejäätmed',
  'bracelet':            'olmejäätmed',
  'ring':                'olmejäätmed',
  'false eyelashes':     'olmejäätmed',
  'makeup sponge':       'olmejäätmed',
  'makeup pad':          'olmejäätmed',
  'q-tip':               'olmejäätmed',
  'bandage':             'olmejäätmed',
  'gauze':               'olmejäätmed',
  'medical tape':        'olmejäätmed',
  'surgical mask':       'olmejäätmed',
  'face mask':           'olmejäätmed',
  'glove':               'olmejäätmed',
  'rubber band':         'olmejäätmed',
  'twist tie':           'olmejäätmed',
  'zip tie':             'olmejäätmed',
  'cable tie':           'olmejäätmed',
  'string':              'olmejäätmed',
  'twine':               'olmejäätmed',
  'rope':                'olmejäätmed',
  'wire':                'olmejäätmed',
  'cable':               'olmejäätmed',
  'extension cord':      'olmejäätmed',
  'headphones':          'olmejäätmed',
  'earbuds':             'olmejäätmed',
  'phone case':          'olmejäätmed',
  'laptop case':         'olmejäätmed',
  'calculator':          'olmejäätmed',
  'remote control':      'olmejäätmed',
  'game controller':     'olmejäätmed',
  'usb drive':           'olmejäätmed',
  'memory card':         'olmejäätmed',
  'floppy disk':          'olmejäätmed',
    // default fallback:
  'default':             'olmejäätmed'
};
// This is a mapping of waste items to their respective categories in Estonian.
export default wasteMap;
