const estonianWasteTypes = {
    // Plastik (Plastics)
    "Plastic": "Plastik",
    "Bottle": "Plastik",
    "Water Bottle": "Plastik",
    "Cup": "Plastik",
    "Bag": "Plastik",
    "Plastic Bag": "Plastik",
    "Container": "Plastik",
    "Plastic Container": "Plastik",
    "Tupperware": "Plastik",
    "Plastic Wrap": "Plastik",
    "Toy": "Plastik",
    "Plastic Bottle": "Plastik",
    "Shampoo Bottle": "Plastik",
    "Lotion Bottle": "Plastik",
    "Soap Dispenser": "Plastik",
    "Toothbrush": "Plastik",
    "Plastic Utensil": "Plastik",
    "Fork": "Plastik",
    "Spoon": "Plastik",
    "Knife": "Plastik",
    "Straw": "Plastik",
    "Plastic Bowl": "Plastik",
    "Plastic Plate": "Plastik",
    "CD": "Plastik",
    "DVD": "Plastik",
    "Plant Pot": "Plastik",
    "Bucket": "Plastik",
    "Laundry Basket": "Plastik",
    "Storage Box": "Plastik",
    "Plastic Chair": "Plastik",
    "Plastic Table": "Plastik",
    "Shower Curtain": "Plastik",
    "Plastic Hanger": "Plastik",
  
    // Paber ja kartong (Paper and Cardboard)
    "Paper": "Paber ja kartong",
    "Cardboard": "Paber ja kartong",
    "Newspaper": "Paber ja kartong",
    "Box": "Paber ja kartong",
    "Carton": "Paber ja kartong",
    "Book": "Paber ja kartong",
    "Magazine": "Paber ja kartong",
    "Envelope": "Paber ja kartong",
    "Paper Bag": "Paber ja kartong",
    "Receipt": "Paber ja kartong",
    "Tissue Paper": "Paber ja kartong",
    "Paper Towel": "Paber ja kartong",
    "Toilet Paper Roll": "Paber ja kartong",
    "Paper Cup": "Paber ja kartong",
    "Paper Plate": "Paber ja kartong",
    "Greeting Card": "Paber ja kartong",
    "Poster": "Paber ja kartong",
    "Flyer": "Paber ja kartong",
    "Business Card": "Paber ja kartong",
    "Notebook": "Paber ja kartong",
    "Catalog": "Paber ja kartong",
    "Paper Napkin": "Paber ja kartong",
    "Sheet Music": "Paber ja kartong",
    "Calendar": "Paber ja kartong",
    "Menu": "Paber ja kartong",
    "Map": "Paber ja kartong",
    "Document": "Paber ja kartong",
    "Letter": "Paber ja kartong",
    "Label": "Paber ja kartong",
    "Sticky Note": "Paber ja kartong",
  
    // Biojäätmed (Bio-waste)
    "Food": "Biojäätmed",
    "Fruit": "Biojäätmed",
    "Vegetable": "Biojäätmed",
    "Bread": "Biojäätmed",
    "Meat": "Biojäätmed",
    "Fish": "Biojäätmed",
    "Coffee Grounds": "Biojäätmed",
    "Tea Bag": "Biojäätmed",
    "Banana": "Biojäätmed",
    "Apple": "Biojäätmed",
    "Orange": "Biojäätmed",
    "Plant": "Biojäätmed",
    "Leaf": "Biojäätmed",
    "Grass": "Biojäätmed",
    "Tree Branch": "Biojäätmed",
    "Flower": "Biojäätmed",
    "Potato": "Biojäätmed",
    "Carrot": "Biojäätmed",
    "Tomato": "Biojäätmed",
    "Lettuce": "Biojäätmed",
    "Onion": "Biojäätmed",
    "Garlic": "Biojäätmed",
    "Egg Shell": "Biojäätmed",
    "Cheese": "Biojäätmed",
    "Pasta": "Biojäätmed",
    "Rice": "Biojäätmed",
    "Cereal": "Biojäätmed",
    "Cookie": "Biojäätmed",
    "Cake": "Biojäätmed",
    "Pizza": "Biojäätmed",
    "Sandwich": "Biojäätmed",
    "Soup": "Biojäätmed",
    "Salad": "Biojäätmed",
    "Peel": "Biojäätmed",
    "Corn": "Biojäätmed",
    "Mushroom": "Biojäätmed",
    "Berry": "Biojäätmed",
    "Nut": "Biojäätmed",
    "Seed": "Biojäätmed",
  
    // Klaas (Glass)
    "Glass": "Klaas",
    "Jar": "Klaas",
    "Glass Bottle": "Klaas",
    "Wine Glass": "Klaas",
    "Mirror": "Klaas",
    "Window": "Klaas",
    "Glass Container": "Klaas",
    "Beer Bottle": "Klaas",
    "Shot Glass": "Klaas",
    "Glass Vase": "Klaas",
    "Drinking Glass": "Klaas",
    "Glass Cup": "Klaas",
    "Glass Bowl": "Klaas",
    "Glass Plate": "Klaas",
    "Perfume Bottle": "Klaas",
    "Medicine Bottle": "Klaas",
    "Light Bulb": "Klaas",
    "Glass Table": "Klaas",
    "Aquarium": "Klaas",
    "Picture Frame": "Klaas",
  
    // Metall (Metal)
    "Metal": "Metall",
    "Can": "Metall",
    "Tin": "Metall",
    "Aluminum": "Metall",
    "Steel": "Metall",
    "Tin Can": "Metall",
    "Soda Can": "Metall",
    "Beer Can": "Metall",
    "Foil": "Metall",
    "Metal Container": "Metall",
    "Metal Bottle": "Metall",
    "Metal Cap": "Metall",
    "Key": "Metall",
    "Lock": "Metall",
    "Coin": "Metall",
    "Paper Clip": "Metall",
    "Staple": "Metall",
    "Nail": "Metall",
    "Screw": "Metall",
    "Wire": "Metall",
    "Metal Hanger": "Metall",
    "Tool": "Metall",
    "Hammer": "Metall",
    "Wrench": "Metall",
    "Pliers": "Metall",
    "Scissors": "Metall",
    "Metal Chair": "Metall",
    "Metal Table": "Metall",
    "Metal Rack": "Metall",
    "Metal Shelf": "Metall",
    "Metal Frame": "Metall",
    "Metal Door": "Metall",
    "Metal Sign": "Metall",
    "Metal Pot": "Metall",
    "Metal Pan": "Metall",
    "Metal Utensil": "Metall",
    "Metal Fork": "Metall",
    "Metal Spoon": "Metall",
    "Metal Knife": "Metall",
  
    // Elektroonika (Electronics)
    // ...existing electronics entries...
    "Remote Control": "Elektroonika",
    "Calculator": "Elektroonika",
    "Clock": "Elektroonika",
    "Watch": "Elektroonika",
    "Printer": "Elektroonika",
    "Scanner": "Elektroonika",
    "Router": "Elektroonika",
    "Modem": "Elektroonika",
    "Speaker": "Elektroonika",
    "Headphones": "Elektroonika",
    "Microphone": "Elektroonika",
    "Game Console": "Elektroonika",
    "Controller": "Elektroonika",
    "Power Supply": "Elektroonika",
    "Hard Drive": "Elektroonika",
    "USB Drive": "Elektroonika",
    "Memory Card": "Elektroonika",
    "DVD Player": "Elektroonika",
    "Blu-ray Player": "Elektroonika",
    "Radio": "Elektroonika",
    "Stereo": "Elektroonika",
    "Air Conditioner": "Elektroonika",
    "Fan": "Elektroonika",
    "Heater": "Elektroonika",
    "Hair Dryer": "Elektroonika",
    "Iron": "Elektroonika",
    "Vacuum Cleaner": "Elektroonika",
    "Washing Machine": "Elektroonika",
    "Dryer": "Elektroonika",
    "Dishwasher": "Elektroonika",
    "Refrigerator": "Elektroonika",
    "Microwave": "Elektroonika",
    "Toaster": "Elektroonika",
    "Coffee Maker": "Elektroonika",
    "Blender": "Elektroonika",
    "Food Processor": "Elektroonika",
  
    // Ohtlikud jäätmed (Hazardous waste)
    // ...existing hazardous entries...
    "Insecticide": "Ohtlikud jäätmed",
    "Pesticide": "Ohtlikud jäätmed",
    "Bleach": "Ohtlikud jäätmed",
    "Acid": "Ohtlikud jäätmed",
    "Solvent": "Ohtlikud jäätmed",
    "Glue": "Ohtlikud jäätmed",
    "Paint Thinner": "Ohtlikud jäätmed",
    "Nail Polish": "Ohtlikud jäätmed",
    "Hair Dye": "Ohtlikud jäätmed",
    "Motor Oil": "Ohtlikud jäätmed",
    "Antifreeze": "Ohtlikud jäätmed",
    "Brake Fluid": "Ohtlikud jäätmed",
    "Gasoline": "Ohtlikud jäätmed",
    "Kerosene": "Ohtlikud jäätmed",
    "Propane Tank": "Ohtlikud jäätmed",
    "Fire Extinguisher": "Ohtlikud jäätmed",
    "Thermometer": "Ohtlikud jäätmed",
    "Fluorescent Bulb": "Ohtlikud jäätmed",
  
    // Pakend (Packaging)
    // ...existing packaging entries...
    "Food Wrapper": "Pakend",
    "Plastic Film": "Pakend",
    "Shrink Wrap": "Pakend",
    "Bubble Wrap": "Pakend",
    "Foam Padding": "Pakend",
    "Packing Peanuts": "Pakend",
    "Cardboard Box": "Pakend",
    "Shipping Box": "Pakend",
    "Gift Box": "Pakend",
    "Gift Wrap": "Pakend",
    "Shopping Bag": "Pakend",
    "Grocery Bag": "Pakend",
    "Wine Box": "Pakend",
    "Beer Box": "Pakend",
    "Six Pack Holder": "Pakend",
    "Egg Carton": "Pakend",
    "Butter Container": "Pakend",
    "Yogurt Container": "Pakend",
    "Ice Cream Container": "Pakend",
    "Condiment Packet": "Pakend",
    "Sauce Packet": "Pakend",
    "Sugar Packet": "Pakend",
    "Salt Packet": "Pakend",
    "Bread Bag": "Pakend",
    "Produce Bag": "Pakend",
    "Meat Package": "Pakend",
    "Fish Package": "Pakend",
    "Frozen Food Box": "Pakend",
    "Cookie Package": "Pakend",
    "Candy Box": "Pakend",
    "Chocolate Wrapper": "Pakend",
    "Gum Package": "Pakend",
    "Medicine Package": "Pakend",
    "Cosmetic Package": "Pakend",
    "Toothpaste Box": "Pakend",
    "Soap Box": "Pakend",
    "Detergent Box": "Pakend",
    "Pet Food Bag": "Pakend",
    "Plant Food Package": "Pakend"
  };
  
  export default estonianWasteTypes;